CREATE TABLE runs (
    id                      TEXT PRIMARY KEY,
    paperclip_run_id        TEXT UNIQUE NOT NULL,
    paperclip_task_id       TEXT NOT NULL,
    paperclip_agent_id      TEXT,
    paperclip_company_id    TEXT,
    jules_session_id        TEXT,
    jules_session_url       TEXT,
    repository              TEXT NOT NULL,
    base_branch             TEXT NOT NULL,
    prompt_hash             TEXT NOT NULL,
    state                   TEXT NOT NULL,
    jules_state             TEXT,
    pr_url                  TEXT,
    pr_number               INTEGER,
    error_code              TEXT,
    error_message           TEXT,
    created_at              TEXT NOT NULL,
    updated_at              TEXT NOT NULL,
    last_polled_at          TEXT,
    next_poll_at            TEXT,
    poll_attempts           INTEGER DEFAULT 0,
    callback_attempts       INTEGER DEFAULT 0,
    callback_delivered_at   TEXT,
    lease_owner             TEXT,
    lease_expires_at        TEXT
);
